# include:
  # - package:flutter_lints/flutter.yaml
  # - package:bloc_lint/recommended.yaml

analyzer:
  errors:
    # treat missing required parameters as an error (not a hint)
    missing_required_param: error
    # treat missing returns as an error (not a hint)
    missing_return: error
    invalid_annotation_target: ignore
  exclude:
    - lib/**/*.g.dart
    - lib/*.g.dart
    - lib/**/*.freezed.dart
    - test/**/*.mocks.dart
  plugins:
    - custom_lint


linter:
  rules:

    # Turn these back on
    avoid_dynamic_calls: false

    # Valid Rules
    unawaited_futures: true
    use_build_context_synchronously: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_interpolation_to_compose_strings: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    use_key_in_widget_constructors: true
    only_throw_errors: true
    directives_ordering: true
    prefer_final_fields: true
    sort_pub_dependencies: false
    unnecessary_parenthesis: true
    require_trailing_commas: false
    depend_on_referenced_packages: false
    sort_child_properties_last: true
    avoid_void_async: true
    always_declare_return_types: true
    missing_whitespace_between_adjacent_strings: true
    sized_box_for_whitespace: true
    no_logic_in_create_state: true
    avoid_unnecessary_containers: true
    avoid_print: true
    avoid_relative_lib_imports: true
    empty_statements: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    valid_regexps: true
    unnecessary_statements: true
    annotate_overrides: true
    avoid_function_literals_in_foreach_calls: true
    avoid_null_checks_in_equality_operators: true
    avoid_unused_constructor_parameters: true
    camel_case_extensions: true
    camel_case_types: true
    empty_constructor_bodies: true
    file_names: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
